version: 3.1:VERSION
services:
 springboot:
 image: 623158369342.dkr.ecr.ap-south-1.amazonaws.com/java-web-app
 restart: always
 ports:
  - 9090:8080
 networks:
  - javaappbridge
networks:
  javaappbridge
