version: "3.1"
services:
 java-web-application:
  image: 623158369342.dkr.ecr.ap-south-1.amazonaws.com/java-web-app:VERSION
  restart: always
  ports:
   - 9090:8080
  networks:
   - javaappbridge
networks:
  javaappbridge:
   driver: bridge
